# -*- coding: utf-8 -*-
"""assignment3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axHrOfLcgN7nSD1C7oI3AN6JKrMXzHO5
"""

#1. Why are functions advantageous to have in your programs?

In python , function available in users programe gives you advantage because we dont have to write one function so many times you just have to give function 
whatever data it need and call that function whenever you want.

#2. When does the code in a function run: when it specified or when it called?

----->
eg:
def test1[1,2,3,4,5]
for i in test1:
  print(i)

  now , whenever i call test1 function then it will give me te list.
  function exicute means function called.when we called the function means it exicute well not only writing a function means exicuting.

#3. What statement creates a function?

we use def for create a function.

#4. What is the difference between a function and a function call?

function:
only declare the value or privious methode of exicuting we can say.it is the block which contain some code or operation
Function call:
it gives user value by exicuting that function.a function complete when we call function.function contain operation but for exicuting that operation 
we need to call function.

#5. How many global scopes are there in a Python program? How many local scopes?

There are 4 scopes in python
1.local
2.global
3.built-in
4.enclosing

#6. What happens to variables in a local scope when the function call returns?

local variable created when function start and get to an end when operation complete.

#7. What is the concept of a return value? Is it possible to have a return value in an expression?
------>


when we use statment like 'print' then the value it hold is 'None Type'. so we use return type statment then the value it hold is not none type.

#8. If a function does not have a return statement, what is the return value of a call to that function?

------>
it will print default statment which is None.

#9. How do you make a function variable refer to the global variable?

A global statement will force a variable in a function to refer to the global variable.

#10. What is the data type of None?
--------->
data type of None is object.it is for null object.

#11. What does the sentence import areallyourpetsnamederic do?

---------->
import will install areallyourpetsnamederic.

#12. If you had a bacon() feature in a spam module, what would you call it after importing spam?
--------->
The function will be called as spam.bacon()

#13. What can you do to save a programme from crashing if it encounters an error?
----->

i will use excaption handleing method.

#14. What is the purpose of the try clause? What is the purpose of the except clause?

----->
sometimes, for preventing our code from crashing we use exception handelling method.
try:
  is for run a code which will not complete if we dont use except under it.
  try statment will include code .
except:
  it will return whatever user define unless and until it will compile time error.